version: '3.5'

services:

  api:
    container_name: game-api
    build: .
    image: game-api
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: database
    depends_on:
      - database

  database:
    container_name: game-database
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
